### ISSUE TITLE
ModuleNotFoundError: No module named 'gorock.rockrawler

### ISSUE THREAD

**Issue by boudar** [abdallah-elsharif/WRock#11]
root@vmi1369511:~/tools/WRock# python3.9 webrock.py
Traceback (most recent call last):
  File "/root/tools/WRock/webrock.py", line 3, in <module>
    from ui.cli import cli
  File "/root/tools/WRock/ui/cli/cli.py", line 2, in <module>
    from ui.cli import app, options
  File "/root/tools/WRock/ui/cli/app.py", line 5, in <module>
    from ui.cli import builder, view, show
  File "/root/tools/WRock/ui/cli/builder.py", line 6, in <module>
    from core.jsanalyzer.anlysis import ExtractorsLoader
  File "/root/tools/WRock/core/jsanalyzer/anlysis.py", line 4, in <module>
    from core.crawler.crawl import crawl
  File "/root/tools/WRock/core/crawler/crawl.py", line 2, in <module>
    from core.crawler.crawler import WebCrawler
  File "/root/tools/WRock/core/crawler/crawler.py", line 4, in <module>
    from gorock.rockrawler import Crawler, CrawlerResult
ModuleNotFoundError: No module named 'gorock.rockrawler

I tested This with python3.9 and Python3.8 it gives the same error

**Comment by boudar** [comment]
i fixed it

**Comment by 0xNinjaCyclone** [comment]
Hello boudar
Your problem seems to be that the gorock module is not built, you have to run `chmod 755 install.sh ; sudo ./install.sh` first.
Thanks
